#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  mkdir -p "$PACKER_TMP_DIR"

  local url_packer_Darwin='https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_darwin_amd64.zip'
  local url_packer_Linux='https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip'

  local url_packer="url_packer_$(uname -s)"
  local fnm_packer="$(basename "${!url_packer}")"
  cache curl "$fnm_packer" "${!url_packer}"

  pushd bin
  unzip -o "${BASEBOX_CACHE}/curl/$fnm_packer"
  (set +f; chmod 755 packer)
  popd
}

bootstrap
