#!/usr/bin/env bash

function _packer_profile {
  local shome="${_packer_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  export PACKER_CACHE_DIR="${DATA}/cache/packer_cache"
}

_packer_profile
