#!/usr/bin/env bash

function _packer_profile {
  local shome="${_packer_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  PACKER_VERSION='1.0.0'
}

_packer_profile
