#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_packer="$(packer --version 2>/dev/null || true)"
  jq -n --arg packer "$ver_packer" '{packer: $packer}'
}

version "$@"
